---
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - ./backrest/tmp:/tmp
      - ./backrest/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      - ./backup/data:/userdata # Mount local paths to backup
      - ./repos:/repos # Mount local repos (optional for remote storage)
      - ./ssh:/.ssh # ssh key for sshfs
      - ./mounts:/mounts # mount via sshfs
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Asia/Kolkata
    ports:
      - "9898:9898"
    restart: unless-stopped
