title: Homelab
theme: dark
color: zinc
headerStyle: clean
statusStyle: dot
hideVersion: true
layout:
  Machines:
    style: row
    columns: 5
  Media:
    style: row
    columns: 4
  Calendar:
    style: row
    columns: 1
  Downloads:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 4
  Apps:
    style: row
    columns: 4
