---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    container_name: speedtest-tracker
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=sqlite
      - APP_URL=${APP_URL}
      - ASSET_URL=${APP_URL}
      - SPEEDTEST_SCHEDULE="*/15 * * * *" # Run every 15 minutes
      - PRUNE_RESULTS_OLDER_THAN=60 # Keep results for 60 days
      - APP_TIMEZONE=Asia/Kolkata
      - DISPLAY_TIMEZONE=Asia/Kolkata
    volumes:
      - ./config:/config
      - ./config/keys:/config/keys

    healthcheck:
      test: curl -fSs http://localhost/api/healthcheck | jq -r .message || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
