services:
  frps:
    image: ghcr.io/fatedier/frps:v0.58.1
    container_name: frps
    restart: unless-stopped
    ports:
      - "7000:7000" # frp communication port
      - "7500:7500" # dashboard port (optional)
      - "8009:8009" # HTTP
      - "8010:8010" # HTTPS
    volumes:
      - ./frps.toml:/etc/frps.toml
    command: -c /etc/frps.toml
